server {
    listen 80;

    root /usr/share/nginx/html; # hna fin kayn dok lfiles dyal frontend déja compilé
    index index.html; 

    location / {
        try_files $uri $uri/ /index.html;
    }
}
