name: CD - Master Pipeline (Deploy)

on:
  workflow_run:
    workflows: ["CI - Tests (Laravel & Angular)"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_REPO: 'reda7856/linux-project'

jobs:
  # 1. BUILD & PUSH DOCKER IMAGES
  build-push:
    name: 🐳 Build & Push Docker Images
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏗️ Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./mon-projet-backend
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:backend-latest

      - name: 🏗️ Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:frontend-latest

  # 2. DEPLOY (SSH)
  deploy:
    name: 🚢 Application Deployment
    needs: build-push
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🛠️ Installer Terraform sur le runner
        uses: hashicorp/setup-terraform@v3

      - name: ⚙️ Configuration du Security Group avec Terraform
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/projet
            git pull origin main
            
            # Utiliser les nouvelles images
            sed -i "s|backend-v1|backend-latest|g" docker-compose.yml
            sed -i "s|Angular_v2|frontend-latest|g" docker-compose.yml
            
            sudo docker compose pull
            sudo docker compose up -d --build
            sudo docker image prune -f
